/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskInput = IDL.Record({
  'output' : IDL.Text,
  'description' : IDL.Text,
  'agentId' : IDL.Nat,
  'state' : IDL.Text,
});
export const Time = IDL.Int;
export const TaskState = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'completedAt' : IDL.Opt(Time),
  'output' : IDL.Opt(IDL.Text),
  'startedAt' : IDL.Opt(Time),
  'createdAt' : Time,
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'agentId' : IDL.Nat,
  'state' : TaskState,
});
export const Agent = IDL.Record({
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'pricePerTask' : IDL.Nat,
  'available' : IDL.Bool,
  'category' : IDL.Text,
});
export const Rating = IDL.Record({
  'user' : IDL.Principal,
  'agentId' : IDL.Nat,
  'comment' : IDL.Opt(IDL.Text),
  'stars' : IDL.Nat,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MarketplaceStats = IDL.Record({
  'totalTasks' : IDL.Nat,
  'totalAgents' : IDL.Nat,
  'totalVolume' : IDL.Nat,
  'completedTasks' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptTask' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelTask' : IDL.Func([IDL.Nat], [], []),
  'completeTask' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'filterEntries' : IDL.Func([TaskInput], [IDL.Vec(IDL.Text)], ['query']),
  'filterTasks' : IDL.Func([TaskInput], [IDL.Vec(Task)], ['query']),
  'filterTasksByEntry' : IDL.Func([TaskInput], [IDL.Vec(TaskInput)], ['query']),
  'filterTasksByOutput' : IDL.Func(
      [TaskInput],
      [IDL.Vec(TaskInput)],
      ['query'],
    ),
  'getAgentAverageRating' : IDL.Func([IDL.Nat], [IDL.Nat, IDL.Nat], ['query']),
  'getAgentById' : IDL.Func([IDL.Nat], [Agent], ['query']),
  'getAgentRatingsByAgent' : IDL.Func([IDL.Nat], [IDL.Vec(Rating)], ['query']),
  'getAgentRatingsCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getAllAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMarketplaceStats' : IDL.Func([], [MarketplaceStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rateAgent' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'registerAgent' : IDL.Func([Agent], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitTask' : IDL.Func([TaskInput], [IDL.Nat], []),
  'toggleAgentAvailability' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskInput = IDL.Record({
    'output' : IDL.Text,
    'description' : IDL.Text,
    'agentId' : IDL.Nat,
    'state' : IDL.Text,
  });
  const Time = IDL.Int;
  const TaskState = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'completedAt' : IDL.Opt(Time),
    'output' : IDL.Opt(IDL.Text),
    'startedAt' : IDL.Opt(Time),
    'createdAt' : Time,
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'agentId' : IDL.Nat,
    'state' : TaskState,
  });
  const Agent = IDL.Record({
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'pricePerTask' : IDL.Nat,
    'available' : IDL.Bool,
    'category' : IDL.Text,
  });
  const Rating = IDL.Record({
    'user' : IDL.Principal,
    'agentId' : IDL.Nat,
    'comment' : IDL.Opt(IDL.Text),
    'stars' : IDL.Nat,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MarketplaceStats = IDL.Record({
    'totalTasks' : IDL.Nat,
    'totalAgents' : IDL.Nat,
    'totalVolume' : IDL.Nat,
    'completedTasks' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptTask' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelTask' : IDL.Func([IDL.Nat], [], []),
    'completeTask' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'filterEntries' : IDL.Func([TaskInput], [IDL.Vec(IDL.Text)], ['query']),
    'filterTasks' : IDL.Func([TaskInput], [IDL.Vec(Task)], ['query']),
    'filterTasksByEntry' : IDL.Func(
        [TaskInput],
        [IDL.Vec(TaskInput)],
        ['query'],
      ),
    'filterTasksByOutput' : IDL.Func(
        [TaskInput],
        [IDL.Vec(TaskInput)],
        ['query'],
      ),
    'getAgentAverageRating' : IDL.Func(
        [IDL.Nat],
        [IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getAgentById' : IDL.Func([IDL.Nat], [Agent], ['query']),
    'getAgentRatingsByAgent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Rating)],
        ['query'],
      ),
    'getAgentRatingsCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getAllAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMarketplaceStats' : IDL.Func([], [MarketplaceStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rateAgent' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'registerAgent' : IDL.Func([Agent], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitTask' : IDL.Func([TaskInput], [IDL.Nat], []),
    'toggleAgentAvailability' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };