/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Agent {
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'pricePerTask' : bigint,
  'available' : boolean,
  'category' : string,
}
export interface MarketplaceStats {
  'totalTasks' : bigint,
  'totalAgents' : bigint,
  'totalVolume' : bigint,
  'completedTasks' : bigint,
}
export interface Rating {
  'user' : Principal,
  'agentId' : bigint,
  'comment' : [] | [string],
  'stars' : bigint,
  'timestamp' : Time,
}
export interface Task {
  'completedAt' : [] | [Time],
  'output' : [] | [string],
  'startedAt' : [] | [Time],
  'createdAt' : Time,
  'user' : Principal,
  'description' : string,
  'agentId' : bigint,
  'state' : TaskState,
}
export interface TaskInput {
  'output' : string,
  'description' : string,
  'agentId' : bigint,
  'state' : string,
}
export type TaskState = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptTask' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelTask' : ActorMethod<[bigint], undefined>,
  'completeTask' : ActorMethod<[bigint, string], undefined>,
  'filterEntries' : ActorMethod<[TaskInput], Array<string>>,
  'filterTasks' : ActorMethod<[TaskInput], Array<Task>>,
  'filterTasksByEntry' : ActorMethod<[TaskInput], Array<TaskInput>>,
  'filterTasksByOutput' : ActorMethod<[TaskInput], Array<TaskInput>>,
  'getAgentAverageRating' : ActorMethod<[bigint], [bigint, bigint]>,
  'getAgentById' : ActorMethod<[bigint], Agent>,
  'getAgentRatingsByAgent' : ActorMethod<[bigint], Array<Rating>>,
  'getAgentRatingsCount' : ActorMethod<[bigint], bigint>,
  'getAllAgents' : ActorMethod<[], Array<Agent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMarketplaceStats' : ActorMethod<[], MarketplaceStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rateAgent' : ActorMethod<[bigint, bigint, [] | [string]], undefined>,
  'registerAgent' : ActorMethod<[Agent], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitTask' : ActorMethod<[TaskInput], bigint>,
  'toggleAgentAvailability' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];